const sectionsData = [
    {
        title:'Resourcces',
        items:[
            {
                name:'About us',
                url:'aboutUs'
            },
            {
                name:'Our Team',
                url:'ourTeam'
            },
            {
                name:'Products',
                url:'products'
            },
            {
                name:'Contact',
                url:'contact'
            },
        ]
    },
    {
        title:'Community',
        items:[
            {
                name:'Feature',
                url:'feature'
            },
            {
                name:'Pricing',
                url:'pricing'
            },
            {
                name:'Credit',
                url:'credit'
            },
            {
                name:'FAQ',
                url:'faq'
            },
        ]
    },
    {
        title:'Quik links',
        items:[
            {
                name:'IOS',
                url:'ios'
            },
            {
                name:'Android',
                url:'android'
            },
            {
                name:'Microsoft',
                url:'microsoft'
            },
            {
                name:'Desktop',
                url:'desktop'
            },
        ]
    },
    {
        title:'More',
        items:[
            {
                name:'Privacy',
                url:'privacy'
            },
            {
                name:'Help',
                url:'help'
            },
            {
                name:'Terms',
                url:'terms'
            },
            {
                name:'FAQ',
                url:'faq'
            },
        ]
    }
]

export default sectionsData